name: tagify
description: "Tagify project flutter."
publish_to: "none"

version: 1.1.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  emoji_picker_flutter: ^4.3.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.1
  package_info_plus: ^8.3.0
  share_handler: ^0.0.22
  flutter_colorpicker: ^1.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  in_app_purchase: ^3.2.1
  google_mobile_ads: ^6.0.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_main_icons_1024_1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/translations/
    - assets/fonts/
    - assets/img/
    - assets/app_main_icons_1024_1024.png

  fonts:
    - family: YoutubeFont
      fonts:
        - asset: assets/fonts/roboto.ttf
        - asset: assets/fonts/roboto-bold.ttf
